# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/qt_forms/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(813, 609)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_for_model_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_for_model_6.setObjectName("label_for_model_6")
        self.gridLayout.addWidget(self.label_for_model_6, 2, 2, 1, 1)
        self.label_for_model_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_for_model_2.setObjectName("label_for_model_2")
        self.gridLayout.addWidget(self.label_for_model_2, 2, 0, 1, 1)

        self.scrollArea_6 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 254, 236))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_model_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.label_model_6.setObjectName("label_model_6")
        self.gridLayout_7.addWidget(self.label_model_6, 0, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout.addWidget(self.scrollArea_6, 3, 2, 1, 1)

        self.label_for_model_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_for_model_5.setObjectName("label_for_model_5")
        self.gridLayout.addWidget(self.label_for_model_5, 0, 2, 1, 1)

        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 254, 236))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_model_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_model_5.setObjectName("label_model_5")
        self.gridLayout_2.addWidget(self.label_model_5, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_3, 1, 2, 1, 1)

        self.label_for_model_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_for_model_1.setAutoFillBackground(False)
        self.label_for_model_1.setObjectName("label_for_model_1")
        self.gridLayout.addWidget(self.label_for_model_1, 0, 0, 1, 1)

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 254, 236))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_model_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_model_1.setObjectName("label_model_1")
        self.gridLayout_4.addWidget(self.label_model_1, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 1)

        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 253, 236))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_model_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_model_3.setObjectName("label_model_3")
        self.gridLayout_3.addWidget(self.label_model_3, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 1, 1, 1, 1)
        self.label_for_model_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_for_model_3.setObjectName("label_for_model_3")
        self.gridLayout.addWidget(self.label_for_model_3, 0, 1, 1, 1)

        self.scrollArea_5 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 253, 236))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_model_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_model_4.setObjectName("label_model_4")
        self.gridLayout_6.addWidget(self.label_model_4, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout.addWidget(self.scrollArea_5, 3, 1, 1, 1)

        self.label_for_model_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_for_model_4.setObjectName("label_for_model_4")
        self.gridLayout.addWidget(self.label_for_model_4, 2, 1, 1, 1)

        self.scrollArea_4 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 254, 236))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_model_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_model_2.setObjectName("label_model_2")
        self.gridLayout_5.addWidget(self.label_model_2, 0, 0, 1, 1)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout.addWidget(self.scrollArea_4, 3, 0, 1, 1)

        self.verticalLayout.addLayout(self.gridLayout)
        mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)
        self.action_add_graph = QtWidgets.QAction(mainwindow)
        self.action_add_graph.setObjectName("action_add_graph")
        self.action_open_image = QtWidgets.QAction(mainwindow)
        self.action_open_image.setObjectName("action_open_image")
        self.action_open_sound = QtWidgets.QAction(mainwindow)
        self.action_open_sound.setObjectName("action_open_sound")
        self.action_close = QtWidgets.QAction(mainwindow)
        self.action_close.setObjectName("action_close")
        self.action_statistics = QtWidgets.QAction(mainwindow)
        self.action_statistics.setObjectName("action_statistics")
        self.action_filter = QtWidgets.QAction(mainwindow)
        self.action_filter.setObjectName("action_filter")
        self.action_deconvolution = QtWidgets.QAction(mainwindow)
        self.action_deconvolution.setObjectName("action_deconvolution")
        self.action_processing_image = QtWidgets.QAction(mainwindow)
        self.action_processing_image.setObjectName("action_processing_image")
        self.menu.addAction(self.action_add_graph)
        self.menu.addAction(self.action_open_image)
        self.menu.addAction(self.action_open_sound)
        self.menu.addSeparator()
        self.menu.addAction(self.action_close)
        self.menu_2.addAction(self.action_statistics)
        self.menu_2.addAction(self.action_filter)
        self.menu_2.addAction(self.action_deconvolution)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_processing_image)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Обработка и анализ данных"))
        self.label_for_model_6.setText(_translate("mainwindow", "TextLabel"))
        self.label_for_model_2.setText(_translate("mainwindow", "TextLabel"))
        self.label_model_6.setText(_translate("mainwindow", "TextLabel"))
        self.label_for_model_5.setText(_translate("mainwindow", "TextLabel"))
        self.label_model_5.setText(_translate("mainwindow", "TextLabel"))
        self.label_for_model_1.setText(_translate("mainwindow", "TextLabel"))
        self.label_model_1.setText(_translate("mainwindow", "TextLabel"))
        self.label_model_3.setText(_translate("mainwindow", "TextLabel"))
        self.label_for_model_3.setText(_translate("mainwindow", "TextLabel"))
        self.label_model_4.setText(_translate("mainwindow", "TextLabel"))
        self.label_for_model_4.setText(_translate("mainwindow", "TextLabel"))
        self.label_model_2.setText(_translate("mainwindow", "TextLabel"))
        self.menu.setTitle(_translate("mainwindow", "Файл"))
        self.menu_2.setTitle(_translate("mainwindow", "Обработка"))
        self.action_add_graph.setText(_translate("mainwindow", "Добавить график"))
        self.action_open_image.setText(_translate("mainwindow", "Открыть изображение"))
        self.action_open_sound.setText(_translate("mainwindow", "Открыть звуковой файл"))
        self.action_close.setText(_translate("mainwindow", "Выход"))
        self.action_statistics.setText(_translate("mainwindow", "Статистики"))
        self.action_filter.setText(_translate("mainwindow", "Фильтр"))
        self.action_deconvolution.setText(_translate("mainwindow", "Деконволюция"))
        self.action_processing_image.setText(_translate("mainwindow", "Изображения..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
